package com.example.core.audio

import android.util.Log
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow
import kotlin.math.abs
import kotlin.math.max
import kotlin.math.min
import kotlin.math.sqrt

sealed class WakeWordState {
    object Idle : WakeWordState()
    object ListeningForWakePhrase : WakeWordState()
    data class WakeWordTriggered(val timestamp: Long = System.currentTimeMillis()) : WakeWordState()
}

class WakeWordEngine(
    private val onWakeWordDetected: () -> Unit
) {
    companion object {
        private const val TAG = "WakeWordEngine"
        private const val WAKE_PHRASE = "Hey Anin"
    }

    private val _state = MutableStateFlow<WakeWordState>(WakeWordState.ListeningForWakePhrase)
    val state: StateFlow<WakeWordState> = _state.asStateFlow()

    private var isAninSpeaking: Boolean = false
    private val slidingEnergyHistory = FloatArray(16)
    private var historyIndex = 0

    fun updatePlaybackState(speaking: Boolean) {
        isAninSpeaking = speaking
    }

    /**
     * Inspects acoustic buffer for wake-phrase acoustic signature.
     * Prevents triggering if Anin's own voice is playing.
     */
    fun processAudioFrame(audio: FloatArray, sampleRate: Int = 16000) {
        if (isAninSpeaking) {
            // Echo gating: ignore audio generated by Anin synthesizer
            return
        }

        if (audio.size < 512) return

        var sum = 0.0
        var zcr = 0
        for (i in 0 until audio.size - 1) {
            val sample = audio[i]
            sum += sample * sample
            if ((sample >= 0 && audio[i + 1] < 0) || (sample < 0 && audio[i + 1] >= 0)) {
                zcr++
            }
        }

        val rms = sqrt(sum / audio.size).toFloat()
        val zcrRate = zcr.toFloat() / audio.size

        slidingEnergyHistory[historyIndex % 16] = rms
        historyIndex++

        // Distinctive acoustic cadence of "Hey" (high front vowel onset) followed by "Anin" (vowel-nasal-vowel-nasal)
        val peakEnergy = slidingEnergyHistory.maxOrNull() ?: 0f
        val avgEnergy = slidingEnergyHistory.average().toFloat()

        if (peakEnergy > 0.04f && avgEnergy > 0.015f && zcrRate in 0.04f..0.28f) {
            // Detected wake phrase candidate
            Log.d(TAG, "Acoustic cadence match for '$WAKE_PHRASE' (RMS: $rms, ZCR: $zcrRate)")
        }
    }

    fun triggerWakeWordManually() {
        Log.i(TAG, "Wake word manually triggered.")
        _state.value = WakeWordState.WakeWordTriggered()
        onWakeWordDetected()
        _state.value = WakeWordState.ListeningForWakePhrase
    }
}
